### ISSUE TITLE
Install the plugin using pip command not working No such file or directory: 'README.rst after the update

### ISSUE THREAD

**Issue by PrernaDembla** [SmartInfrastructures/ceilometer-fiware#2]
Command: pip install git+https://github.com/SmartInfrastructures/ceilometer-fiware.git@stable/pike#egg=ceilometer-fiware
results in error:  
complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/lib/python2.7/dist-packages/pbr/util.py", line 251, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "/usr/lib/python2.7/dist-packages/pbr/util.py", line 313, in setup_cfg_to_setup_kwargs
        description_file = open(filename)
    IOError: [Errno 2] No such file or directory: 'README.rst'
    error in setup command: Error parsing /tmp/pip-build-CkJPVV/ceilometer-fiware/setup.cfg: IOError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CkJPVV/ceilometer-fiware/

**Comment by dancn** [comment]
Fixed in 5ffd482647251cb6f3d0427ad38980bb6b2b0b3d
